name: Package AURA

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARCHIVE_NAME: AURA_${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Build Archive
        run: |
          7z a "${{ env.ARCHIVE_NAME }}.7z" . \
            -xr!.git \
            -xr!.github \
            -xr!README.md \
            -xr!.gitignore

      - name: Create Release with changelog
        uses: notlmn/release-with-changelog@v3
        with:
          header: "### Changelog"
          include-hash: true
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Github
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE_NAME }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}